spring:
  application:
    name: spring_auth_server
  datasource:
    url: jdbc:sqlite:./db/auth.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop

  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 8989
  address: 0.0.0.0
storage:
  location: upload_dir

